blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<int:id>', views.post_detail, name="post_detail"),
]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PB', 'Published'
        REJECTED = 'RJ', 'Rejected'

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_posts")
    title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.SlugField(max_length=250)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post


# Create your views here.


def index(request):
    return HttpResponse("index")


def post_list(request):
    posts = Post.published.all()
    context = {
        'posts': posts,
    }
    return render(request, "blog/list.html", context)


def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    context = {
        'post': post,
    }
    return render(request, "blog/detail.html", context)

blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% block title %}post Detail{% endblock %}
{% block head %}{% endblock %}
{% block content %}
<h1>{{ post.title }} by {{ post.author }}</h1>
    <h2>{{ post.description|linebreaks }}</h2>
    <hr>
    {{ post.publish }}


{% endblock %}

blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% block title %}post list{% endblock %}
{% block head %}{% endblock %}
{% block content %}
    <h1>Post List</h1>
    {% for post in posts %}
        <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
        <p>{{ post.description|truncatewords:4 }}</p>
    {% endfor %}

{% endblock %}

blog/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog | {% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

</head>
<body>
{% include 'partials/header.html' %}
{% include 'partials/navigation.html' %}
{% block content %}{% endblock %}
{% include 'partials/footer.html' %}


</body>
</html>